/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Level = ("OFF" | "FATAL" | "ERROR" | "WARN" | "INFO" | "DEBUG" | "TRACE" | "ALL")

export interface Logs {
  runtimeLogViewData: RuntimeLogViewData;
  [k: string]: unknown;
}
export interface RuntimeLogViewData {
  entries: RuntimeLogEntryLsp[];
  [k: string]: unknown;
}
export interface RuntimeLogEntryLsp {
  category: string;
  level: Level;
  message: string;
  processElement: string;
  project: string;
  request: string;
  throwableInformationMsg: string;
  timestamp: string;
  userDialogId: string;
  [k: string]: unknown;
}
